# Section 2: Deep Learning and TensorFlow Fundamentals

**In this notebooke we're going to cover some of the most fundamental concepts of tensors using TensorFlow**

More specifically, we're going to cover:
* Introductions to tensors
* Getting information from tensors
* Manipulating tensors
* Tensors & NumPy
* Using @tf.function (a way to speed up your regular Python functions)
* Using GPUs with TensorFlow (or TPUs)
* Exercises to try for yourself

## Import Section

In [1]:
import tensorflow as tf
import numpy as np

In [3]:
print('TensorFlow Version: ', tf.__version__)

TensorFlow Version:  2.10.1


## Video Activities

### 16. Creating your first tensors with TensorFlow and tf.constant()

In [4]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [5]:
# Check dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [9]:
# Create a vector
vector = tf.constant([1,2])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2])>

In [10]:
vector.ndim

1

In [21]:
matrix = tf.constant(
    [
        [10, 7],
        [7, 10],
    ]
)
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]])>

In [22]:
matrix.ndim

2

In [23]:
matrix_2 = tf.constant(
    [
        [10.,7.],
        [3.,2.],
        [8.,9.]
    ],
    dtype = tf.float16
)

matrix_2

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [24]:
matrix_2.ndim

2

In [25]:
# Create a tensor - A tensor has 3 dimensions

tensor = tf.constant(
    [
        [
            [1,2,3],
            [4,5,6]
        ],
        [
            [8,9,10],
            [11,12,13]
        ],
        [
            [14, 15, 16],
            [17, 18, 19]
        ],
    ]
)

tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 8,  9, 10],
        [11, 12, 13]],

       [[14, 15, 16],
        [17, 18, 19]]])>

In [26]:
tensor.ndim

3

What has been created so far:
* Scalar: Single number
* Vector: Number with direction
* Matrix: 2D array of numbers
* Tensor: N-Dimensional array of numbers

### 17. Creating tensors with TensorFlow and tf.Variable()

In [27]:
tf.Variable

tensorflow.python.ops.variables.Variable

In [28]:
# Create the same tensor using tf.Variable()
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])

changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>)

In [33]:
# Change one element in changeable_tensor
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7])>

In [34]:
# Change one element in unchangeable_tensor (try)
unchangeable_tensor[0].assing(7)
unchangeable_tensor

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assing'

### 18. Creating random tensors with TensorFlow

Tensors of some arbitrary size that contains random numbers

In [36]:
# Create 2 equal random tensors 
random_1 = tf.random.Generator.from_seed(42)
random_2 = tf.random.Generator.from_seed(42)

random_1 = random_1.normal(shape = (3,2))
random_2 = random_2.normal(shape = (3,2))

random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### 19. Shuffling the order of tensors

In [37]:
not_shuffled = tf.constant([
    [10, 7],
    [3, 4],
    [2, 5],
])

In [38]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]])>

In [39]:
shuffled = tf.random.shuffle(
    not_shuffled,
    42
)

In [40]:
shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]])>

### 20. Creating tensors from NumPy arrays

The main difference between NumPy arrays and TensorFlow Tensors is that tensors can be run on a GPU for faster numerical computing

If trying to reshape a tensor we have to have the dimensions to add up to the total of elements, for example:

`[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24] -> Total = 24 | shape=(24,)`

Reshape can be `shape=(2,3,4)` which means `2 * 3 * 4 = 24`, but if we try `shape=(2,3,5)` which means `2 * 3 * 5 = 30` then we will receive an error like this:

* **TypeError:** Eager execution of tf.constant with unsupported shape. Tensor [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24] (converted from [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]) has 24 elements, but got `shape` (2, 3, 5) with 30 elements).

In [10]:
# Create tensor of all ones
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [11]:
# Create a tensor of all zeros
tf.zeros([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [19]:
# Turn NumpPy arrays into tensors
A_np = np.arange(1, 25, dtype = np.int32)

A_tf = tf.constant(A_np, shape = (2,3,4))
A_tf

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])>

### 21. Getting information from your tensors (tensor attributes)

| **Attribute**       | **Description**                                                                                     | **Code**                      |
| ------------------- | --------------------------------------------------------------------------------------------------- | ----------------------------- |
| *Shape*             | The length (number of elements) of each of the dimensions of a tensor                               | `tensor.shape`                |
| *Rank*              | The number of tensor dimensions. **Ranks:** `scalar = 0`, `vector = 1`, `matrix = 2`, `tensor = n`  | `tensor.ndim`                 |
| *Axis or Dimension* | A praticular dimension of a tensor                                                                | `tensor[0]`, `tensor[:,1]`... |
| *Size*              | The total number of items in the tensor                                                             | `tf.size(tensor)`             |

In [2]:
# Create a rank 4 tensor (4D tensor)
rank_4_tensor = tf.zeros(
    shape = [2,3,4,5]
)

rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [13]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [11]:
rank_4_tensor[1]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [12]:
rank_4_tensor[:, 1]

<tf.Tensor: shape=(2, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [18]:
# Get various attributes of our tensors
print('Every element datatype:', rank_4_tensor.dtype)
print('Dimensions/Rank:', rank_4_tensor.ndim)
print('Tensor Shape:', rank_4_tensor.shape)
print('Elements along the 0 axis:', rank_4_tensor.shape[0])
print('Elements along the last axis:', rank_4_tensor.shape[0])
print('Total amount of elements in our tensor:', tf.size(rank_4_tensor))
print('Total amount of elements in our tensor:', tf.size(rank_4_tensor).numpy())

Every element datatype: <dtype: 'float32'>
Dimensions/Rank: 4
Tensor Shape: (2, 3, 4, 5)
Elements along the 0 axis: 2
Elements along the last axis: 2
Total amount of elements in our tensor: tf.Tensor(120, shape=(), dtype=int32)
Total amount of elements in our tensor: 120


### 22. Indexing and expanding tensors

*Tensors can be indexed just like Python Lists*

* [tf.newaxis - Add dimension](https://www.tensorflow.org/api_docs/python/tf#newaxis)
* [tf.expand_dims - Add dimension](https://www.tensorflow.org/api_docs/python/tf/expand_dims)

In [20]:
# Get first 2 elements of each dimension
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [21]:
# Get the first element from each dimension from each index except from the final one
rank_4_tensor[:1, :1, :1]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [23]:
# Add extra dimension to the end of a newly rank 2 tensor(2D)
rank_2_tensor = tf.constant(
    [
        [10, 7],
        [3, 4]
    ]
)

rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [26]:
# Get last item of each row of our rank_2_tensor
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4])>

In [27]:
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]])>

In [28]:
# Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis = -1) # "-1" means expand the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]])>

In [29]:
tf.expand_dims(rank_2_tensor, axis = 0) # "0" means expand the 0 axis

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]])>

### 23. Manipulating Tensors - Tensor Operations

TensorFlow built-in functions for Tensor Operations:
* [tf.math](https://www.tensorflow.org/api_docs/python/tf/math)

#### Basic Operations
`+`, `-`, `*`, `/`

In [32]:
tensor = tf.constant(
    [
        [10, 7],
        [3, 4]
    ]
)

In [33]:
tensor + 10, tensor - 10, tensor * 10, tensor / 10

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[20, 17],
        [13, 14]])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 0, -3],
        [-7, -6]])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[100,  70],
        [ 30,  40]])>,
 <tf.Tensor: shape=(2, 2), dtype=float64, numpy=
 array([[1. , 0.7],
        [0.3, 0.4]])>)

In [34]:
# We can use the TensorFlow built-in function too
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]])>

### 24-26. Matrix multiplication with tensors

In ML, matrix multiplication is one of the most common tensor operations.

There are 2 rules our tensors (or matrices) need to fulfill if we're going to matrix multiply them:
1. The inner dimensions must match shape1 = (3, **2**) shape2 = (**2**, 3)
2. The resulting matrix has the shape of the inner dimensions 
   * shape1 = (3, **2**) shape2 = (**2**, 3)
   * shape1 * shape2
   * **Result:** shape3 = (3, 2)


Generally, when preforming matrix multiplication on two tensors and one of the axes doesn't line up, we will transpose rather than reshape one of them to satisfy the matrix multiplication rules

#### 24. Matrix multiplication with tensors - P1

* [What's matrix multiplication - Math is Fun](https://www.mathsisfun.com/algebra/matrix-multiplying.html)
* [Matrix Multiplication - Visualization](http://matrixmultiplication.xyz/)
* [Matrix Multiplication in TensorFlow - tf.linalg.matmul](https://www.tensorflow.org/api_docs/python/tf/linalg/matmul)

In [35]:
print(tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


In [36]:
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]])>

In [41]:
# Matrix Multiplication with Python operator '@'
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]])>

In [42]:
replica = tf.constant(
    [
        [1, 2, 5],
        [7, 2, 1],
        [3, 3, 3]
    ]
)

replica_mult = tf.constant(
    [
        [3, 5],
        [6, 7],
        [1, 8]
    ]
)

replica, replica_mult, tf.matmul(replica, replica_mult)

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[1, 2, 5],
        [7, 2, 1],
        [3, 3, 3]])>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[3, 5],
        [6, 7],
        [1, 8]])>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[20, 59],
        [34, 57],
        [30, 60]])>)

#### 25. Matrix multiplication with tensors - P2

In [45]:
tf.matmul(replica_mult, replica_mult)

InvalidArgumentError: {{function_node __wrapped__MatMul_device_/job:localhost/replica:0/task:0/device:CPU:0}} Matrix size-incompatible: In[0]: [3,2], In[1]: [3,2] [Op:MatMul]

In [48]:
replica_mult, tf.matmul(tf.transpose(replica_mult), replica_mult)

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[3, 5],
        [6, 7],
        [1, 8]])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 46,  65],
        [ 65, 138]])>)

#### 26. Matrix multiplication with tensors - P3

**The dot product**

Matrix multiplication is also referred to as the dot product.

You can perform matrix multiplication using:
* `tf.matmul()`
* `tf.tensordor()`

In [54]:
replica_mult

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 5],
       [6, 7],
       [1, 8]])>

In [53]:
# Perform the dor product on replica_mult and replica_mult (One of them transposed)
tf.tensordot(tf.transpose(replica_mult), replica_mult, 1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 46,  65],
       [ 65, 138]])>

In [55]:
# Perform the dor product on replica_mult and replica_mult (One of them reshaped)
tf.matmul(
    replica_mult, 
    tf.reshape(
        replica_mult,
        shape=(2, 3)
    )
)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[44, 20, 58],
       [67, 37, 92],
       [59, 13, 70]])>

In [57]:
# Check replica_mult, reshape replica_mult and transposed replica_mult
print('Normal replica_mult')
print(replica_mult, '\n')
print('Reshaped replica_mult (2, 3)')
print(tf.reshape(replica_mult, (2, 3)), '\n')
print('Transposed replica_mult')
print(tf.transpose(replica_mult), '\n')

Normal replica_mult
tf.Tensor(
[[3 5]
 [6 7]
 [1 8]], shape=(3, 2), dtype=int32) 

Reshaped replica_mult (2, 3)
tf.Tensor(
[[3 5 6]
 [7 1 8]], shape=(2, 3), dtype=int32) 

Transposed replica_mult
tf.Tensor(
[[3 6 1]
 [5 7 8]], shape=(2, 3), dtype=int32) 



### 27. Changing the datatype of tensors

* [Mixed Precision - TensorFlow](https://www.tensorflow.org/guide/mixed_precision)

In [58]:
# Tensor with default datatype (float32)
B = tf.constant([1.7, 7.4])
B.dtype

tf.float32

In [59]:
C = tf.constant([7, 10])
C.dtype

tf.int32

In [62]:
# Change from float32 to float16 (Reduced Precision)
B = tf.cast(B, dtype= tf.float16)
B

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>

In [64]:
C = tf.cast(
    C, 
    dtype = tf.float16
)
C

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([ 7., 10.], dtype=float16)>

### 28. Tensor Aggregation (Finding the min, max, mean & more)

### 29. Tensor Troubleshooting example (Updating tensor datatypes)

### 30. Finding the positional minimum and maximum of a tensor (argmin and argmax)

### 31. Squeezing a tensor (removing all 1-dimension axes)

### 32. One-hot encoding tensors

### 33. Trying out more tensor math operations

### 34. Exploring TensorFlow and NumPy's compatibility

### 35. Making sure our tensor operations run really fast on GPUs