# Section 2: Deep Learning and TensorFlow Fundamentals

**In this notebooke we're going to cover some of the most fundamental concepts of tensors using TensorFlow**

More specifically, we're going to cover:
* Introductions to tensors
* Getting information from tensors
* Manipulating tensors
* Tensors & NumPy
* Using @tf.function (a way to speed up your regular Python functions)
* Using GPUs with TensorFlow (or TPUs)
* Exercises to try for yourself

## Import Section

In [8]:
import tensorflow as tf
import numpy as np

In [3]:
print('TensorFlow Version: ', tf.__version__)

TensorFlow Version:  2.10.1


## Video Activities

### 16. Creating your first tensors with TensorFlow and tf.constant()

In [4]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [5]:
# Check dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [9]:
# Create a vector
vector = tf.constant([1,2])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2])>

In [10]:
vector.ndim

1

In [21]:
matrix = tf.constant(
    [
        [10, 7],
        [7, 10],
    ]
)
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]])>

In [22]:
matrix.ndim

2

In [23]:
matrix_2 = tf.constant(
    [
        [10.,7.],
        [3.,2.],
        [8.,9.]
    ],
    dtype = tf.float16
)

matrix_2

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [24]:
matrix_2.ndim

2

In [25]:
# Create a tensor - A tensor has 3 dimensions

tensor = tf.constant(
    [
        [
            [1,2,3],
            [4,5,6]
        ],
        [
            [8,9,10],
            [11,12,13]
        ],
        [
            [14, 15, 16],
            [17, 18, 19]
        ],
    ]
)

tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 8,  9, 10],
        [11, 12, 13]],

       [[14, 15, 16],
        [17, 18, 19]]])>

In [26]:
tensor.ndim

3

What has been created so far:
* Scalar: Single number
* Vector: Number with direction
* Matrix: 2D array of numbers
* Tensor: N-Dimensional array of numbers

### 17. Creating tensors with TensorFlow and tf.Variable()

In [27]:
tf.Variable

tensorflow.python.ops.variables.Variable

In [28]:
# Create the same tensor using tf.Variable()
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])

changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>)

In [33]:
# Change one element in changeable_tensor
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7])>

In [34]:
# Change one element in unchangeable_tensor (try)
unchangeable_tensor[0].assing(7)
unchangeable_tensor

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assing'

### 18. Creating random tensors with TensorFlow

Tensors of some arbitrary size that contains random numbers

In [36]:
# Create 2 equal random tensors 
random_1 = tf.random.Generator.from_seed(42)
random_2 = tf.random.Generator.from_seed(42)

random_1 = random_1.normal(shape = (3,2))
random_2 = random_2.normal(shape = (3,2))

random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### 19. Shuffling the order of tensors

In [37]:
not_shuffled = tf.constant([
    [10, 7],
    [3, 4],
    [2, 5],
])

In [38]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]])>

In [39]:
shuffled = tf.random.shuffle(
    not_shuffled,
    42
)

In [40]:
shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]])>

### 20. Creating tensors from NumPy arrays

The main difference between NumPy arrays and TensorFlow Tensors is that tensors can be run on a GPU for faster numerical computing

If trying to reshape a tensor we have to have the dimensions to add up to the total of elements, for example:

`[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24] -> Total = 24 | shape=(24,)`

Reshape can be `shape=(2,3,4)` which means `2 * 3 * 4 = 24`, but if we try `shape=(2,3,5)` which means `2 * 3 * 5 = 30` then we will receive an error like this:

* **TypeError:** Eager execution of tf.constant with unsupported shape. Tensor [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24] (converted from [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]) has 24 elements, but got `shape` (2, 3, 5) with 30 elements).

In [10]:
# Create tensor of all ones
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [11]:
# Create a tensor of all zeros
tf.zeros([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [19]:
# Turn NumpPy arrays into tensors
A_np = np.arange(1, 25, dtype = np.int32)

A_tf = tf.constant(A_np, shape = (2,3,4))
A_tf

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])>

### 21. Getting information from your tensors (tensor attributes)

### 22. Indexing and expanding tensors

### 23. Manipulating tensors with basic operations

### Matrix multiplication with tensors

#### 24. Matrix multiplication with tensors - P1

#### 25. Matrix multiplication with tensors - P2

#### 26. Matrix multiplication with tensors - P3

### 27. Changing the datatype of tensors

### 28. Tensor Aggregation (Finding the min, max, mean & more)

### 29. Tensor Troubleshooting example (Updating tensor datatypes)

### 30. Finding the positional minimum and maximum of a tensor (argmin and argmax)

### 31. Squeezing a tensor (removing all 1-dimension axes)

### 32. One-hot encoding tensors

### 33. Trying out more tensor math operations

### 34. Exploring TensorFlow and NumPy's compatibility

### 35. Making sure our tensor operations run really fast on GPUs