# Section 2: Deep Learning and TensorFlow Fundamentals

**In this notebooke we're going to cover some of the most fundamental concepts of tensors using TensorFlow**

More specifically, we're going to cover:
* Introductions to tensors
* Getting information from tensors
* Manipulating tensors
* Tensors & NumPy
* Using @tf.function (a way to speed up your regular Python functions)
* Using GPUs with TensorFlow (or TPUs)
* Exercises to try for yourself

## Import Section

In [73]:
import tensorflow as tf
import numpy as np

In [2]:
print('TensorFlow Version: ', tf.__version__)

TensorFlow Version:  2.10.1


## Video Activities

### 16. Creating your first tensors with TensorFlow and tf.constant()

In [3]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
# Check dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [5]:
# Create a vector
vector = tf.constant([1,2])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2])>

In [6]:
vector.ndim

1

In [7]:
matrix = tf.constant(
    [
        [10, 7],
        [7, 10],
    ]
)
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]])>

In [8]:
matrix.ndim

2

In [9]:
matrix_2 = tf.constant(
    [
        [10.,7.],
        [3.,2.],
        [8.,9.]
    ],
    dtype = tf.float16
)

matrix_2

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [10]:
matrix_2.ndim

2

In [11]:
# Create a tensor - A tensor has 3 dimensions

tensor = tf.constant(
    [
        [
            [1,2,3],
            [4,5,6]
        ],
        [
            [8,9,10],
            [11,12,13]
        ],
        [
            [14, 15, 16],
            [17, 18, 19]
        ],
    ]
)

tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 8,  9, 10],
        [11, 12, 13]],

       [[14, 15, 16],
        [17, 18, 19]]])>

In [12]:
tensor.ndim

3

What has been created so far:
* Scalar: Single number
* Vector: Number with direction
* Matrix: 2D array of numbers
* Tensor: N-Dimensional array of numbers

### 17. Creating tensors with TensorFlow and tf.Variable()

In [13]:
tf.Variable

tensorflow.python.ops.variables.Variable

In [14]:
# Create the same tensor using tf.Variable()
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])

changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>)

In [15]:
# Change one element in changeable_tensor
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7])>

In [16]:
# Change one element in unchangeable_tensor (try)
unchangeable_tensor[0].assing(7)
unchangeable_tensor

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assing'

### 18. Creating random tensors with TensorFlow

Tensors of some arbitrary size that contains random numbers

In [17]:
# Create 2 equal random tensors 
random_1 = tf.random.Generator.from_seed(42)
random_2 = tf.random.Generator.from_seed(42)

random_1 = random_1.normal(shape = (3,2))
random_2 = random_2.normal(shape = (3,2))

random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### 19. Shuffling the order of tensors

In [18]:
not_shuffled = tf.constant([
    [10, 7],
    [3, 4],
    [2, 5],
])

In [19]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]])>

In [20]:
shuffled = tf.random.shuffle(
    not_shuffled,
    42
)

In [21]:
shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]])>

### 20. Creating tensors from NumPy arrays

The main difference between NumPy arrays and TensorFlow Tensors is that tensors can be run on a GPU for faster numerical computing

If trying to reshape a tensor we have to have the dimensions to add up to the total of elements, for example:

`[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24] -> Total = 24 | shape=(24,)`

Reshape can be `shape=(2,3,4)` which means `2 * 3 * 4 = 24`, but if we try `shape=(2,3,5)` which means `2 * 3 * 5 = 30` then we will receive an error like this:

* **TypeError:** Eager execution of tf.constant with unsupported shape. Tensor [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24] (converted from [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]) has 24 elements, but got `shape` (2, 3, 5) with 30 elements).

In [30]:
# Create tensor of all ones
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [31]:
# Create a tensor of all zeros
tf.zeros([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [32]:
# Turn NumpPy arrays into tensors
A_np = np.arange(1, 25, dtype = np.int32)

A_tf = tf.constant(A_np, shape = (2,3,4))
A_tf

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])>

### 21. Getting information from your tensors (tensor attributes)

| **Attribute**       | **Description**                                                                                     | **Code**                      |
| ------------------- | --------------------------------------------------------------------------------------------------- | ----------------------------- |
| *Shape*             | The length (number of elements) of each of the dimensions of a tensor                               | `tensor.shape`                |
| *Rank*              | The number of tensor dimensions. **Ranks:** `scalar = 0`, `vector = 1`, `matrix = 2`, `tensor = n`  | `tensor.ndim`                 |
| *Axis or Dimension* | A praticular dimension of a tensor                                                                | `tensor[0]`, `tensor[:,1]`... |
| *Size*              | The total number of items in the tensor                                                             | `tf.size(tensor)`             |

In [25]:
# Create a rank 4 tensor (4D tensor)
rank_4_tensor = tf.zeros(
    shape = [2,3,4,5]
)

rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [26]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [27]:
rank_4_tensor[1]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [28]:
rank_4_tensor[:, 1]

<tf.Tensor: shape=(2, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [29]:
# Get various attributes of our tensors
print('Every element datatype:', rank_4_tensor.dtype)
print('Dimensions/Rank:', rank_4_tensor.ndim)
print('Tensor Shape:', rank_4_tensor.shape)
print('Elements along the 0 axis:', rank_4_tensor.shape[0])
print('Elements along the last axis:', rank_4_tensor.shape[0])
print('Total amount of elements in our tensor:', tf.size(rank_4_tensor))
print('Total amount of elements in our tensor:', tf.size(rank_4_tensor).numpy())

Every element datatype: <dtype: 'float32'>
Dimensions/Rank: 4
Tensor Shape: (2, 3, 4, 5)
Elements along the 0 axis: 2
Elements along the last axis: 2
Total amount of elements in our tensor: tf.Tensor(120, shape=(), dtype=int32)
Total amount of elements in our tensor: 120


### 22. Indexing and expanding tensors

*Tensors can be indexed just like Python Lists*

* [tf.newaxis - Add dimension](https://www.tensorflow.org/api_docs/python/tf#newaxis)
* [tf.expand_dims - Add dimension](https://www.tensorflow.org/api_docs/python/tf/expand_dims)

In [33]:
# Get first 2 elements of each dimension
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [34]:
# Get the first element from each dimension from each index except from the final one
rank_4_tensor[:1, :1, :1]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [35]:
# Add extra dimension to the end of a newly rank 2 tensor(2D)
rank_2_tensor = tf.constant(
    [
        [10, 7],
        [3, 4]
    ]
)

rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [36]:
# Get last item of each row of our rank_2_tensor
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4])>

In [37]:
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]])>

In [38]:
# Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis = -1) # "-1" means expand the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]])>

In [39]:
tf.expand_dims(rank_2_tensor, axis = 0) # "0" means expand the 0 axis

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]])>

### 23. Manipulating Tensors - Tensor Operations

TensorFlow built-in functions for Tensor Operations:
* [tf.math](https://www.tensorflow.org/api_docs/python/tf/math)

#### Basic Operations
`+`, `-`, `*`, `/`

In [40]:
tensor = tf.constant(
    [
        [10, 7],
        [3, 4]
    ]
)

In [41]:
tensor + 10, tensor - 10, tensor * 10, tensor / 10

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[20, 17],
        [13, 14]])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 0, -3],
        [-7, -6]])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[100,  70],
        [ 30,  40]])>,
 <tf.Tensor: shape=(2, 2), dtype=float64, numpy=
 array([[1. , 0.7],
        [0.3, 0.4]])>)

In [42]:
# We can use the TensorFlow built-in function too
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]])>

### 24-26. Matrix multiplication with tensors

In ML, matrix multiplication is one of the most common tensor operations.

There are 2 rules our tensors (or matrices) need to fulfill if we're going to matrix multiply them:
1. The inner dimensions must match shape1 = (3, **2**) shape2 = (**2**, 3)
2. The resulting matrix has the shape of the inner dimensions 
   * shape1 = (3, **2**) shape2 = (**2**, 3)
   * shape1 * shape2
   * **Result:** shape3 = (3, 2)


Generally, when preforming matrix multiplication on two tensors and one of the axes doesn't line up, we will transpose rather than reshape one of them to satisfy the matrix multiplication rules

#### 24. Matrix multiplication with tensors - P1

* [What's matrix multiplication - Math is Fun](https://www.mathsisfun.com/algebra/matrix-multiplying.html)
* [Matrix Multiplication - Visualization](http://matrixmultiplication.xyz/)
* [Matrix Multiplication in TensorFlow - tf.linalg.matmul](https://www.tensorflow.org/api_docs/python/tf/linalg/matmul)

In [43]:
print(tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


In [44]:
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]])>

In [45]:
# Matrix Multiplication with Python operator '@'
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]])>

In [46]:
replica = tf.constant(
    [
        [1, 2, 5],
        [7, 2, 1],
        [3, 3, 3]
    ]
)

replica_mult = tf.constant(
    [
        [3, 5],
        [6, 7],
        [1, 8]
    ]
)

replica, replica_mult, tf.matmul(replica, replica_mult)

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[1, 2, 5],
        [7, 2, 1],
        [3, 3, 3]])>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[3, 5],
        [6, 7],
        [1, 8]])>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[20, 59],
        [34, 57],
        [30, 60]])>)

#### 25. Matrix multiplication with tensors - P2

In [47]:
tf.matmul(replica_mult, replica_mult)

InvalidArgumentError: {{function_node __wrapped__MatMul_device_/job:localhost/replica:0/task:0/device:CPU:0}} Matrix size-incompatible: In[0]: [3,2], In[1]: [3,2] [Op:MatMul]

In [48]:
replica_mult, tf.matmul(tf.transpose(replica_mult), replica_mult)

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[3, 5],
        [6, 7],
        [1, 8]])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 46,  65],
        [ 65, 138]])>)

#### 26. Matrix multiplication with tensors - P3

**The dot product**

Matrix multiplication is also referred to as the dot product.

You can perform matrix multiplication using:
* `tf.matmul()`
* `tf.tensordor()`

In [49]:
replica_mult

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 5],
       [6, 7],
       [1, 8]])>

In [50]:
# Perform the dor product on replica_mult and replica_mult (One of them transposed)
tf.tensordot(tf.transpose(replica_mult), replica_mult, 1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 46,  65],
       [ 65, 138]])>

In [51]:
# Perform the dor product on replica_mult and replica_mult (One of them reshaped)
tf.matmul(
    replica_mult, 
    tf.reshape(
        replica_mult,
        shape=(2, 3)
    )
)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[44, 20, 58],
       [67, 37, 92],
       [59, 13, 70]])>

In [52]:
# Check replica_mult, reshape replica_mult and transposed replica_mult
print('Normal replica_mult')
print(replica_mult, '\n')
print('Reshaped replica_mult (2, 3)')
print(tf.reshape(replica_mult, (2, 3)), '\n')
print('Transposed replica_mult')
print(tf.transpose(replica_mult), '\n')

Normal replica_mult
tf.Tensor(
[[3 5]
 [6 7]
 [1 8]], shape=(3, 2), dtype=int32) 

Reshaped replica_mult (2, 3)
tf.Tensor(
[[3 5 6]
 [7 1 8]], shape=(2, 3), dtype=int32) 

Transposed replica_mult
tf.Tensor(
[[3 6 1]
 [5 7 8]], shape=(2, 3), dtype=int32) 



### 27. Changing the datatype of tensors

* [Mixed Precision - TensorFlow](https://www.tensorflow.org/guide/mixed_precision)

In [53]:
# Tensor with default datatype (float32)
B = tf.constant([1.7, 7.4])
B.dtype

tf.float32

In [54]:
C = tf.constant([7, 10])
C.dtype

tf.int32

In [55]:
# Change from float32 to float16 (Reduced Precision)
B = tf.cast(B, dtype= tf.float16)
B

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>

In [56]:
C = tf.cast(
    C, 
    dtype = tf.float16
)
C

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([ 7., 10.], dtype=float16)>

### 28. Tensor Aggregation (Finding the min, max, mean & more)

**Aggregating Tensors**

Aggregate tensors refer to multi-dimensional arrays or structures composed of individual tensors that are combined together through a specific aggregation operation, such as concatenation, stacking, or reduction. These operations allow for the merging or consolidation of tensors along specified dimensions, resulting in a single tensor that encapsulates the information from the original tensors. Aggregate tensors are commonly used in various machine learning tasks, such as data preprocessing, feature engineering, and model interpretation.

Let's go through the following forms of aggregation:

| **Aggregation** | **Description**                                                             | **Code**                 |
| --------------- | --------------------------------------------------------------------------- | ------------------------ |
| Absolute        | Computes the absolute value of a tensor.                                    | `tf.abs(tensor)`         |
| Minimum         | Computes the `tf.math.minimum` of elements across dimensions of a tensor.   | `tf.reduce_min(tensor)`  |
| Maximum         | Computes `tf.math.maximum` of elements across dimensions of a tensor.       | `tf.reduce_max(tensor)`  |
| Mean            | Computes the mean of elements across dimensions of a tensor.                | `tf.reduce_mean(tensor)` |
| Sum             | Computes the sum of elements across dimensions of a tensor.                 | `tf.reduce_sum(tensor)`  |


**There are more Aggregation operations in the tf.math module, go and check the [docs](https://www.tensorflow.org/api_docs/python/tf/math) to see more.**

In [62]:
D = tf.constant(np.random.randint(0, 100, size=50))
D

<tf.Tensor: shape=(50,), dtype=int32, numpy=
array([93, 65, 22, 33, 21, 58,  4, 49, 88, 74, 68,  7, 64, 41, 25, 11, 85,
        7, 61, 92, 60, 18, 55, 71,  4, 90, 20, 46, 48, 68, 46, 76, 52,  9,
       36, 50, 23,  2, 21,  1, 80,  4,  4, 18, 63, 97, 43, 75,  8, 36])>

In [63]:
# Get the absolute values - Take all the negative values and turn 'em into positive
tf.abs(D)

<tf.Tensor: shape=(50,), dtype=int32, numpy=
array([93, 65, 22, 33, 21, 58,  4, 49, 88, 74, 68,  7, 64, 41, 25, 11, 85,
        7, 61, 92, 60, 18, 55, 71,  4, 90, 20, 46, 48, 68, 46, 76, 52,  9,
       36, 50, 23,  2, 21,  1, 80,  4,  4, 18, 63, 97, 43, 75,  8, 36])>

In [66]:
tf.reduce_min(D), tf.reduce_max(D), tf.reduce_mean(D), tf.reduce_sum(D)


(<tf.Tensor: shape=(), dtype=int32, numpy=1>,
 <tf.Tensor: shape=(), dtype=int32, numpy=97>,
 <tf.Tensor: shape=(), dtype=int32, numpy=43>,
 <tf.Tensor: shape=(), dtype=int32, numpy=2192>)

### 29. Tensor Troubleshooting example (Updating tensor datatypes)

In [80]:
# Won't work with int dtype tensors, we have to cast them to float or use tensorflow_probability module (but this module needs tensorflow >= 2.16)
tf.math.reduce_variance(tf.cast(D, dtype=tf.float32)), tf.math.reduce_std(tf.cast(D, dtype=tf.float32))

(<tf.Tensor: shape=(), dtype=float32, numpy=848.2544>,
 <tf.Tensor: shape=(), dtype=float32, numpy=29.124807>)

### 30. Finding the positional minimum and maximum of a tensor (argmin and argmax)

In [84]:
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [86]:
tf.argmax(F), tf.argmin(F)

(<tf.Tensor: shape=(), dtype=int64, numpy=42>,
 <tf.Tensor: shape=(), dtype=int64, numpy=16>)

In [88]:
F[42], F[16]

(<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>)

In [89]:
F[tf.argmax(F)] == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [90]:
F[tf.argmin(F)] == tf.reduce_min(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

### 31. Squeezing a tensor (removing all 1-dimension axes)

* [tf.squeeze - Docs](https://www.tensorflow.org/api_docs/python/tf/squeeze)

In [92]:
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1,1,1,1,50))

G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [93]:
G_squezeed = tf.squeeze(G)
G_squezeed

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [95]:
G.shape, ' | ', G_squezeed.shape

(TensorShape([1, 1, 1, 1, 50]), ' | ', TensorShape([50]))

### 32. One-hot encoding tensors

One-hot encoding is a process used in machine learning and data preprocessing to convert categorical variables into a binary matrix format. In this encoding scheme, each category is represented as a binary vector where only one bit is "hot" (1) while all others are "cold" (0). Each bit corresponds to a unique category, and the position of the "hot" bit indicates the category's index in the original categorical variable. One-hot encoding allows categorical data to be represented in a numerical format suitable for machine learning algorithms, where each category is treated as an independent binary feature.

* [One-Hot Encoding - Spanish](https://interactivechaos.com/es/manual/tutorial-de-machine-learning/one-hot-encoding)
* [What is One-Hot Encoding](https://www.educative.io/blog/one-hot-encoding)
* [tf.one_hot - TensorFlow Docs](https://www.tensorflow.org/api_docs/python/tf/one_hot)

tf.one_hot requires the indices to be **a tensor of indices** and depth to be a **scalar**

In [99]:
# Create a list of indices
some_list = [0,1,2,3] # Let's say this represents red, green, blue, purple

# One-Hot encode our list of indices
tf.one_hot(
    some_list,
    depth = len(some_list)
)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [101]:
# Specify custom values for one hot encoding - Rarely used in practice
tf.one_hot(
    some_list, 
    depth = 4, 
    on_value = 'Yo! I love deep learning', 
    off_value = 'I also like to dance'
)

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'Yo! I love deep learning', b'I also like to dance',
        b'I also like to dance', b'I also like to dance'],
       [b'I also like to dance', b'Yo! I love deep learning',
        b'I also like to dance', b'I also like to dance'],
       [b'I also like to dance', b'I also like to dance',
        b'Yo! I love deep learning', b'I also like to dance'],
       [b'I also like to dance', b'I also like to dance',
        b'I also like to dance', b'Yo! I love deep learning']],
      dtype=object)>

### 33. Trying out more tensor math operations

A few common math operations are:
| Operation   | Description                                            | Code                  |
| ----------- | ------------------------------------------------------ | --------------------- |
| Squaring    | Computes square of x element-wise.                     | `tf.square(tensor)`   |
| Log         | Computes natural logarithm of x element-wise.          | `tf.math.log(tensor)` |
| Square Root | Computes element-wise square root of the input tensor. | `tf.sqrt(tensor)`     |

For more operations you can check the [math module documentation](https://www.tensorflow.org/api_docs/python/tf/math)

In [102]:
H = tf.range(1, 10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [106]:
print('Square:', tf.square(H))
print('Log:', tf.math.log(tf.cast(H, dtype=tf.float32)))
print('Sqrt:', tf.sqrt(tf.cast(H, dtype=tf.float32)))

Square: tf.Tensor([ 1  4  9 16 25 36 49 64 81], shape=(9,), dtype=int32)
Log: tf.Tensor(
[0.        0.6931472 1.0986123 1.3862944 1.609438  1.7917595 1.9459102
 2.0794415 2.1972246], shape=(9,), dtype=float32)
Sqrt: tf.Tensor(
[1.        1.4142135 1.7320508 2.        2.2360678 2.4494896 2.6457512
 2.828427  3.       ], shape=(9,), dtype=float32)


### 34. Exploring TensorFlow and NumPy's compatibility

TensorFlow interacts really good with NumPy arrays

In [113]:
# Create tensor from NumPy array
J = tf.constant(np.array([3.,7.,10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [114]:
# Convert back tensor to NumPy array
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [115]:
# Convert tensor J to a NumPy array
J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [122]:
# The default types of each are slightly different
numpy_J = tf.constant(np.array([3., 7., 10.]))
tensor_J = tf.constant([3., 7., 10.])

# Check datatypes of each
'From NumPy array -> ', numpy_J.dtype, '| From python list -> ', tensor_J.dtype

('From NumPy array -> ', tf.float64, '| From python list -> ', tf.float32)

### 35. Making sure our tensor operations run really fast on GPUs

In [123]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [124]:
!nvidia-smi

Mon Apr  8 14:16:35 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 551.86                 Driver Version: 551.86         CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                     TCC/WDDM  | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce GTX 1650 ...  WDDM  |   00000000:08:00.0  On |                  N/A |
| 35%   41C    P8             11W /  100W |    2761MiB /   4096MiB |      4%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

**Note:** If you have access to a CUDA-enabled GPU, TensorFlow will automatically use it whenever possible for tensor operations